apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: auth-service-monitor
  labels:
    app: auth
    release: prometheus-helm
spec:
  jobLabel: app
  endpoints:
  - interval: 30s
    port: auth
    path: /swagger-stats/metrics
  selector:
    matchLabels:
      app: auth