apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: expiration-service-monitor
  labels:
    app: expiration
    release: prometheus-helm
spec:
  jobLabel: app
  endpoints:
  - interval: 30s
    port: expiration
    path: /swagger-stats/metrics
  selector:
    matchLabels:
      app: expiration