apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tickets-mongo-pv-claim
spec:
  storageClassName: local-storage
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi