apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: orders-mongo-pv-claim
spec:
  storageClassName: do-block-storage
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi