apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-depl
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: mroc/client
          # image: us.gcr.io/microservice-nodejs-2/client
          env:
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: CLUSTER_BASE_URL
              value: "http://ingress-nginx-controller.ingress-nginx.svc.cluster.local"
          resources:
            requests:
              memory: "150Mi"
              cpu: 0.15
---
apiVersion: v1
kind: Service
metadata:
  name: client-clusterip-srv
spec:
  type: NodePort
  externalTrafficPolicy: Local
  selector:
    app: client
  ports:
    - name: client
      protocol: TCP
      port: 3000
      targetPort: 3000