apiVersion: v1
kind: PersistentVolume
metadata:
  name: expiration-redis-pv
spec:
  storageClassName: local-storage
  claimRef:
    name: expiration-redis-pv-claim
    namespace: default
  persistentVolumeReclaimPolicy: Retain
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /run/desktop/mnt/host/wsl/data/expiration-redis-pv