resources:
- ../../base
- ./auth-mongo-pv.yaml
- ./expiration-redis-pv.yaml
- ./orders-mongo-pv.yaml
- ./payments-mongo-pv.yaml
- ./tickets-mongo-pv.yaml

configMapGenerator:
- name: application-config
  envs:
  - application.properties

patches:
- target:
    kind: Ingress
    name: ingress-srv
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: local.seqo.io
- target:
    kind: PersistentVolumeClaim
  patch: |-
    - op: replace
      path: /spec/storageClassName
      value: local-storage