apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: orders-mongo-pv-claim
spec:
  storageClassName: local-storage
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: orders-mongo-pv
spec:
  storageClassName: local-storage
  claimRef:
    name: orders-mongo-pv-claim
    namespace: default
  persistentVolumeReclaimPolicy: Retain
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /run/desktop/mnt/host/wsl/data/orders-mongo-pv