apiVersion: v1
kind: PersistentVolume
metadata:
  name: payments-mongo-pv
spec:
  storageClassName: local-storage
  claimRef:
    name: payments-mongo-pv-claim
    namespace: default
  persistentVolumeReclaimPolicy: Retain
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /run/desktop/mnt/host/wsl/data/payments-mongo-pv